# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BiOS
email: biaoliu_2007@163.com
description: iOS Samples

exclude: ['deploy_website.sh']

baseurl: "/BiOS"
url: "https://biaowu.github.com"

github_username:  BiaoWu

# Build settings
markdown: kramdown
